# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TemperatureItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, temperature: int=None):  # noqa: E501
        """TemperatureItem - a model defined in Swagger

        :param temperature: The temperature of this TemperatureItem.  # noqa: E501
        :type temperature: int
        """
        self.swagger_types = {
            'temperature': int
        }

        self.attribute_map = {
            'temperature': 'temperature'
        }
        self._temperature = temperature

    @classmethod
    def from_dict(cls, dikt) -> 'TemperatureItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TemperatureItem of this TemperatureItem.  # noqa: E501
        :rtype: TemperatureItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def temperature(self) -> int:
        """Gets the temperature of this TemperatureItem.


        :return: The temperature of this TemperatureItem.
        :rtype: int
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature: int):
        """Sets the temperature of this TemperatureItem.


        :param temperature: The temperature of this TemperatureItem.
        :type temperature: int
        """
        if temperature is None:
            raise ValueError("Invalid value for `temperature`, must not be `None`")  # noqa: E501

        self._temperature = temperature
